[package]
name = "descriptive-serial"
version = "0.1.0"
authors = ["Jeremy DeJournett <jcdejournett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.11.13"
serial = "0.4.0"
indextree = "4.3.1"
